### ISSUE TITLE
Cannot read data after write with cidVersion=1

### ISSUE THREAD

**Issue by alanshaw** [ipfs/js-ipfs-mfs#12]

**Comment by achingbrain** [comment]
It seems this is because nodes added to IPFS using v1 CIDs are returned from `ipld.dag.get` with v0 CIDs.  See ipld/js-ipld#157

**Comment by achingbrain** [comment]
Could you try again with `v0.5.1`?  There's now a test that [writes with a v1 CID  and reads the data back](https://github.com/ipfs/js-ipfs-mfs/blob/master/test/write.spec.js#L507-L516) which passes.

**Comment by achingbrain** [comment]
This should be fixed now, please re-open if it's not.
